server {
    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
    server_name antarctic.games www.antarctic.games api.antarctic.games;

    ssl_certificate /etc/letsencrypt/live/antarctic.games/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/antarctic.games/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /wisp/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Host $host;
        include /etc/nginx/proxy_params;
        proxy_pass http://127.0.0.1:8080;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    location / {
        proxy_set_header X-Forwarded-Host $host;
        include /etc/nginx/proxy_params;
        proxy_pass http://127.0.0.1:8080;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name antarctic.games www.antarctic.games api.antarctic.games;
    return 301 https://$host$request_uri;
}
